# Generated by Django 4.0.6 on 2022-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
