# Generated by Django 4.0.6 on 2022-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_category_remove_team_name_alter_team_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team_category',
        ),
    ]
